### ISSUE TITLE
Settings: ignore keys in referenced schema

### ISSUE THREAD

**Issue by jezscha** [pypeclub/OpenPype#1600]
# Description
As referencing of other shema is used and not always there is necessary to use all keys from the referenced schema, it would be great to have `ignore_keys` attribute with list of keys which should be ignored. It means those will not be added into gui and not collected into settings data.
 
There is several instance where would this feature come handful. 

# Example of usage:
In this example only `argument_1` will be used.

### Referencing of schema:
```
{
    "type": "schema",
    "name": "some_referenced_shema",
    "ignore_keys": ["argument_1"]
}
```

### Referenced schema content `some_referenced_shema.json`:
```
{
    "type": "dict",
    "key": "category",
    "children": [
        {
            "type": "dict",
            "key": "argument_1",
            "children": [
                {
                    "type": "boolean",
                    "key": "sub_argument_1",
                }
            ]
        },
        {
            "type": "dict",
            "key": "argument_2",
            "children": [
                {
                    "type": "boolean",
                    "key": "sub_argument_2",
                }
            ]
        }
    ]
}
```

**Comment by mkolar** [comment]
Very good idea. We had a brief chat about it with @iLLiCiTiT and came to two tweaks with the proposal.

1. This feature should work for templates, rather than schemas. Schemas should stay purely for simplifying the structure, while templates are for usage in multiple places and already can carry some metadata that modify their behaviour
2. the ignored keys will need to be specified as a full relative path to the key so we can ignore keys that are deeper in the hierarchy. for example `plugins/publish/key1`
