### ISSUE TITLE
Disable workfile autoload in Launcher

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#1852]
### Feature

It would be nice to have ability to disable automatic loading of workfile on deman in Launcher. For some specific task, there could be very big scene file as a last workfile that you don't want to load in some particular case. This could be possibly implemented as right+click context menu with checkbox.

[cuID:PYPE-1276]

**Comment by kalisp** [comment]
You mean it should be per task or per application? And should it be persistent? And should it be per user or system wide?

**Comment by antirotor** [comment]
Yes, as I imagine it, you would right click on app icon in launcher and in context menu, you'll have item like "[X] Autoload latest workfile"...
![image](https://user-images.githubusercontent.com/33513211/142423987-65a66c3e-9cfa-4fbb-b7bb-e94c62a54e29.png)

**Comment by mkolar** [comment]
I actually ran into this quite a lot last and this week. You have it globally on because it makes sense for most contexts, but sometime there is a massive scene that's crashing for instance and you ned to override this option ad hoc. 

I'm not sure we need it persistent but it would be nice.

**Comment by kalisp** [comment]
There are a couple of options being discussed right now:
- add checkbox to bottom section of Launcher (under application, next to the "rewind" icon) with "Do not open last workfile"
-     disadvantage is that some icons might not be a app launcher icons and some host cannot be opened without workfile 
- add option "Do not open last workfile" to context menu visible on app icons
-     disadvantages are same as above, might be too cluttered on multiple installed versions of host app
- add context menu to the column with tasks (right column in Launcher) with some icon highlighting that "Do not open last workfile" option was selected

Majority of opinions lean to choice be persistent, differences are if it should be per Task or per Host app.

(Issue with persistence is where to store it - Local Settings (LS app doesnt count with this right now) - somewhere on machine (keyring - only applicable on Tray apps where keyring is required).

**Comment by antirotor** [comment]
I believe it has to be Task based. Ideally Task/Application group based. Because typical usage of this feature is like this:

I have a Task, lets call it Layout. I am creating layout is Maya, loading tons of stuff to scene, so much so opening this scene in Maya takes literally minutes. So I don't want to automatically load latest workfile whenever I launch Maya on this task, becase I occasionally want to open older version of the scene and with this will make me waiting for minutes until latest scene is loaded just for me to close it right away and load whatever I want.

But this doesn't apply to all Tasks, not even all layout tasks, just the one I want. This also doesn't apply to Maya on the project.

So I think this means selecting particular task and be able to right+click on application group to see checkbox "disable auto wokrfile loading". When this is checked, icon on application group should change (have some small badge on it perhaps?) so artist knows something is different. This settings should then be saved locally on artist computer and it should completely ignore whatever is set in studio wide settings.

That's my idea. Right+click context menu in this case is ok by me and it can be even added to tooltip description on application group mouseover.

**Comment by BigRoy** [comment]
_I've disabled auto load on open here so I'm not sure I'm the best candidate to provide decent input for users who like to approach it with that setting enabled by default._

Also, these are just some thoughts - sorry if it's a messy comment.

> add checkbox to bottom section of Launcher (under application, next to the "rewind" icon) with "Do not open last workfile"

I personally like that. Something that is a visual indicator that I could instantly see whether it's currently enabled - for me. I feel this really is a **personal setting** you might want to toggle. And yes, you might not want it for a specific shot just because it's a heavy or slow loading asset or for a specific task.

---

Then I think it would be good to have an option where specific tasks (or task types, etc.) - whatever filter makes sense - can be set up "force autoload to be disabled" or at least recommend it in some other way. It could even be that for those files where you have that setting enabled you get a very tiny little extra dropdown/menu indicating whether you'd want to load the latest workfile.

So you click Maya -> "Yes". But having that happen only sometimes I think will be root of confusion. Which makes me bring it back to - shouldn't this just be a User setting in general? :) Something that yes, can be toggled inside the Launcher?

Maybe having three settings for auto load:
- Yes
- Always ask (the little menu I described as extra click)
- Disabled

And these could then be toggled in the bottom bar next to the history icon.

**Comment by tokejepsen** [comment]
I would maybe instead have it as a launch option, so each application version has two variants:

- Maya 2019
- Maya 2019 (blank)

This would translate well to for example Ftrack launching.
