### ISSUE TITLE
Maya: Disable rendering of all lights - Render Setup / Deadline

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#2241]
## Feature

Normally Maya will render all enabled lights in scene. If - for some reason - you want to selectively render lights based on render setup settings, you can do it by manually setting this option in render setup or using `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` set to `0`.

However Deadline will always override this environment variable unless job includes `RenderSetupIncludeLights` set to zero in **PluginInfo** part of job definition.

Having this set per scene is useful so I propose to add it to render instance settings.

Related #2215 

[cuID:1rw2mw7]

**Comment by BigRoy** [comment]
Where would we like the Studio/Artists to control this setting? I'd recommend always setting the environment variable and controlling it somewhere in the pipeline whether this is enabled or not. Mostly because the setting does **NOT** get saved into the scene. 

And thus it could be that Artist A opening scene X could render it differently than Artist B opening scene X just because of a difference in that particular setting on their machine.

For render submissions to Deadline I'd say to just submit along `RenderSetupIncludeLights` with the state of the current artist submitting the scene. So then at least the Deadline render is consistent with what the artist is seeing when they test render on their machine. We'd just need to make sure aside of that that there's some consistency on whether `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` is 1 or 0.

**Comment by antirotor** [comment]
This is related to default render instance settings configurable by Settings UI. So far I have UI like this:

![image](https://user-images.githubusercontent.com/33513211/149194927-5bc3ca98-3c2b-434f-b5bb-2e39fcedfc7b.png)

and I thought I'll add it there too, enabled by default to comply with Maya default settings. From this it would be pulled directly to render instance so artist can turn it on/off and script action should synchronize it with Render Setup settings.

**Comment by BigRoy** [comment]
We actually hit this issue again Today - for now we [hotfixed it](https://github.com/BigRoy/OpenPype/commit/64cf5863980fc79fa66682e8d96f4e578f5ebab5) but would love to see a "common ground" on how we'd like to tackle it.

Since these are not saved per scene I'd still encourage to set the `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` globally for your pipeline. With worst case scenario allowing shot-based overrides. But honestly, I'd just force the value to `0` by default. Disable adding all lights by default. In that scenario the user can still add lights as he'd like - but if the value is enabled then the user could never exclude lights in a render setup layer (unless he's explicitly hiding them).

Thoughts?

**Comment by antirotor** [comment]
So what about this - set it globally for pipeline. Not sure exactly where - probably in render creator settings - that will allow it to be configured per project. This will be then passed to the Deadline job.

**Comment by BigRoy** [comment]
> So what about this - set it globally for pipeline.

To me that's the best first step likely, yes. A prelaunch hook might need to then set the `MAYA_RENDER_SETUP_INCLUDE_ALL_LIGHTS` env var on Maya launch based on the settings?

> probably in render creator settings

As long as it's disconnected from the actual Create Render instance logic etc. seems fine with me.
