### ISSUE TITLE
Maya: work file not saved before publish

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2743]
When publishing in Maya without saving the workfile first, there is an issue with copying the wrong workfile to publish.

We should **always** save the workfile before publish.

Is there any reason for this filtering in 
OpenPype\openpype\hosts\maya\plugins\publish\save_scene.py ?

[cuID:OP-2668]

**Comment by BigRoy** [comment]
> Is there any reason for this filtering in OpenPype\openpype\hosts\maya\plugins\publish\save_scene.py ?

I think this might have been speed constraints in our older pipeline - saving could just take long. [It looks like a close to copy of our studio config](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/save_scene.py#L14). And we just loved living on the edge.

There shouldn't be any reason not to in general, but the use case you're describing would already work by adding [`"workfile"` family to this SaveScene plug-in](https://github.com/pypeclub/OpenPype/blob/926eb5b95ece6feb27957c04633bdfb3785e9c7a/openpype/hosts/maya/plugins/publish/save_scene.py#L12)

Also, we could add checking for modifications as in [our plugin](https://github.com/Colorbleed/colorbleed-config/blob/acre/colorbleed/plugins/maya/publish/save_scene.py#L14) - that at least skips saving if the user saved just before publishing already.

**Comment by BigRoy** [comment]
> (but we should not do it twice before and after publish)

I've set up PR #2744 but that excludes this particular point. It is an optimization but also prone to error.

Technically we could **store** some data during Save Scene like `context.data["sceneSavedDuringPublish"] = True` and then instead of saving a new version in [IncrementCurrentFile](https://github.com/pypeclub/OpenPype/blob/926eb5b95ece6feb27957c04633bdfb3785e9c7a/openpype/hosts/maya/plugins/publish/increment_current_file_deadline.py#L33-L40) we could e.g. do:

```python
# psuedocode
    # Rename current file so that Maya knows the new filepath
    cmds.file(rename=new_filepath)
    
    if context.data.get("sceneSavedDuringPublish", False):
        # Copy file without saving to optimize
        shutil.copyfile(current_filepath, new_filepath)
    else:
        # Save with the correct file type associated with extension
        if new_filepath.endswith(".ma"):
            fileType = "mayaAscii"
        elif new_filepath.endswith(".mb"):
            fileType = "mayaBinary"
    
        cmds.file(save=True, force=True, type=fileType)
```
 
However that opens another can of worms of potential issues and I'd save that for a separate PR if this issue has a high severity.

**Comment by BigRoy** [comment]
@m-u-r-p-h-y this is now fixed for Maya and Houdini with:

- #2744
- #2747 

Do we still want to keep this open?

**Comment by m-u-r-p-h-y** [comment]
not necessary. closing as it was resolved . . .   thx
