### ISSUE TITLE
Maya2022: Collect render layers

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#2861]
**Describe the bug**
There is an error during lighting publish in Maya2022

I took working lighting file from Maya2020 and tried to publish in Maya2022

See error
```
// Error: pyblish.plugin : Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "C:\Program Files (x86)\OpenPype\openpype\hosts\maya\plugins\publish\collect_render.py", line 237, in process
TypeError: 'dict_keys' object is not subscriptable
Traceback (most recent call last):
  File "C:\Program Files (x86)\OpenPype\dependencies\pyblish\plugin.py", line 522, in __explicit_process
    runner(*args)
  File "<string>", line 237, in process
TypeError: 'dict_keys' object is not subscriptable // 
```

OP 3.8.2

**Screenshots**
![image](https://user-images.githubusercontent.com/352795/157477965-d5087dfa-5c20-4761-88e2-597ba6338f51.png)

[cuID:27wtk6h]

**Comment by BigRoy** [comment]
I see you're mentioning OP 3.8.2.

This issue is already solved. 
This [PR code line](https://github.com/pypeclub/OpenPype/pull/2445/files#diff-c323f9c7150e69e037e670402e307afc4db96ee4874e6f9e06afd454c921ecf8R237) has fixed that.
Which is also in the [latest develop](https://github.com/pypeclub/OpenPype/blob/develop/openpype/hosts/maya/plugins/publish/collect_render.py#L237).

Can you confirm with running latest develop?
Before that PR Maya 2022 (Py3 logic) had much more bugs. :)

**Comment by m-u-r-p-h-y** [comment]
Ohh I thought it was already deployed. Will double-check and close the issue eventually. Thanks
