### ISSUE TITLE
Maya: Importing Pymel in Maya 2020.4 is failing

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3233]
**Describe the bug**

`import pymel.core as pm`

is not working in Maya2020 launched from OP

`# Error: NameError: file C:\Program Files\Autodesk\Maya2020\Python\lib\site-packages\pymel\core\__init__.py line 77: name 'windows' is not defined # `

**To Reproduce**

see the step above

**Expected behavior**

vanilla Maya is importing pymel with no issue

Maya 2020, Cut Number 202011110415
or
Maya2020.4

[cuID:OP-3287]

**Comment by m-u-r-p-h-y** [comment]
Another user reported the same issue on MacOS

![image](https://user-images.githubusercontent.com/352795/170291035-04ace98b-a5f7-422a-8777-3bb1debf9977.png)

**Comment by m-u-r-p-h-y** [comment]
I still have trouble consistently replicating the issue. It is very random and it seems it is dependent on loading the other plugins like arnold etc.

**Comment by antirotor** [comment]
My research shows that this is directly connected to Maya 2020 and MtoA 5.1.3. It might affect different versions of MtoA and Maya simply because pymel is very sensitive to node definitions and it just happens that MtoA 5.1.3 is defining `aiSky` node in pymel incompatible way.

There is probably solution to in from OpenPype point of view - monkeypatch that pymel function that is checking for node superclass definitions using assert, but by my opinion it is not worth the effort as this doesn't happen in Maya 2022 and MtoA 5.1.3 or even in Maya 2023.

**Comment by 2-REC** [comment]
Having the same issue (when trying to load a component via the OpenPype loader) in Maya 2020.2 with MtoA 5.1.3.1.

The problem occurs when importing Pymel if MtoA is loaded.

So as a "solution", the following can bypass the issue:
* unload MtoA
* import Pymel module
* load MtoA

Once the Pymel module has been imported, following imports will not have the problem, even if MtoA is loaded.

It is of course not a real solution, but if somehow stuck with these 2 versions, it might be better than nothing.
