### ISSUE TITLE
Maya: Review Image plane attribute

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3272]
**Describe the bug**

animation review instance attributes are not working while I was testing the new feature with multiple instances in #3269

**To Reproduce**
two review instances 
one with image plane on
other with image plane off

The resulting playblasts will have image plane on in both cases

![image](https://user-images.githubusercontent.com/352795/171437462-83bc3b9a-eab2-4fd3-b418-3d9199650a1b.png)

[cuID:2eqzt4u]

**Comment by moonyuet** [comment]
The issue comes from the _extract_thumbnail.py_ in ./plugin/publish folder. 
it doesn't set up any condition to tell the system to not to add the image if the image_plane attribute is turned off.
Instead of 
` _, thumbnail = os.path.split(playblast)`
I adjust the code with this
`
        image_plane = instance.data.get("imagePlane")
        if image_plane:
            _, thumbnail = os.path.split(playblast)
        else:
            return`

This will solve the review image plane attribute issue. 
![image](https://user-images.githubusercontent.com/64118225/180764261-edf7f17b-52a2-4653-918f-5a14a52274b7.png)

By the way, I am wondering if you guys also want to turn off the playblast option when the image plane turns off. I also checked the _exteact_playblast.py_ in ./plugin/publish/ . The code seems to bind the playblast options when image plane turns on/off.
