### ISSUE TITLE
Deadline GlobalJobPreLoad is expecting openpype on all jobs

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3664]
**Describe the bug**

there is a problem with GlobalJobPreLoad.py which is expecting openpype exe to be defined for all jobs, including the ones submited without openpype

**To Reproduce**

submit any job in Deadline Monitor

**Expected behavior**
GlobalJobPreLoad.py should skip openpype executable resolution if the job is not coming from OP

**Screenshots**
```
Error: Global job preload script 'C:\ProgramData\Thinkbox\Deadline10\workers\WS01\plugins\62fa138dbb4eeb1460fc1f71\GlobalJobPreLoad.py': SyntaxError : ('invalid syntax', ('C:\\ProgramData\\Thinkbox\\Deadline10\\workers\\WS01\\plugins\\62fa138dbb4eeb1460fc1f71\\GlobalJobPreLoad.py', 37, 49, '        print(f"   ! path is not a build: {path}")\n')) (FranticX.Scripting.PythonNetException)
   at Python.Runtime.Runtime.CheckExceptionOccurred()
   at Python.Runtime.PythonEngine.ModuleFromString(String name, String code, String fileName)
   at FranticX.Scripting.PythonNetScriptEngine.ExecuteFile(String scriptFile, String moduleName, Boolean optimizeCode)
   at Deadline.Plugins.PluginWrapper.d()
   at Deadline.Plugins.PluginWrapper.StartJob(String& outMessage, AbortLevel& abortLevel)

```

[cuID:OP-3724]

**Comment by BigRoy** [comment]
This is solely due to the [OP v2 (`pype`) backwards compatibility at the end](https://github.com/pypeclub/OpenPype/blob/b88e537ca9dbc1033f5cbc49d82ca6e21c6266fc/openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py#L332-L333).

Probably best is to just [return here](https://github.com/pypeclub/OpenPype/blob/b88e537ca9dbc1033f5cbc49d82ca6e21c6266fc/openpype/modules/deadline/repository/custom/plugins/GlobalJobPreLoad.py#L281-L282) when both of these are not set and you should be good to go.

**Comment by antirotor** [comment]
Also the syntax error is probably related to python 3 syntax in the code, so this requires more recent versions of deadline

**Comment by m-u-r-p-h-y** [comment]
> Also the syntax error is probably related to python 3 syntax in the code, so this requires more recent versions of deadline

this is the latest 10.1.23.6
