### ISSUE TITLE
Reset window position

### ISSUE THREAD

**Issue by m-u-r-p-h-y** [pypeclub/OpenPype#3921]
**Is your feature request related to a problem? Please describe.**

It is happening quite often recently that opening an OP window (Scene Inventory in Maya for example) is not working for the user.

There is only a message in Script Editor `Using existing QApplication..`

![image](https://user-images.githubusercontent.com/352795/192515060-19c79d7b-20df-4f19-b466-861128705b75.png)

**Describe the solution you'd like**

This "error" means the window is already opened, but it is hidden for the user outside of the visible area. (happening a lot with dual monitor setups and remoting to that machine)

We could implement some hot key to reset the window position back to the default location (and print the hotkey to the console with the `Using existing QApplication..` message

[cuID:OP-4154]

**Comment by BigRoy** [comment]
This is due to how Maya stores the Window positions. You're mentioning Scene Inventory and that indeed hooks into Maya's "remember my last UI position" by having the `saveWindowPref` property set. See [here](https://github.com/pypeclub/OpenPype/blob/ac0252f9c6819173bf8a64cda8c8668a7f80e18c/openpype/tools/sceneinventory/window.py#L43-L44)

Removing that will also ignore Maya trying to open and restore the UI to the last known position and size. Since this is so specific to Maya and thus alters how these tools actually show in Maya compared to other tools we might be better of removing that particular property and ensure how the tools open across the different hosts keep decent standards.

If one of those standards is the need to be able to remember last window size and position, then we can implement it so that it works across all DCC implementations.

I suspect removing `saveWindowPref` property would already avoid the bug in Maya.

Can you confirm this issue only occurred with the Scene Inventory? It's the only tool that still had that flag set.

**Comment by m-u-r-p-h-y** [comment]
Yes, it was reported by our clients with Scene Inventory only.
