### ISSUE TITLE
Publishing: Plugin progress indication

### ISSUE THREAD

**Issue by antirotor** [pypeclub/OpenPype#413]
## Indicating progress in Pyblish plugins

For longer running plugins it would be great to see their progress. This is visual mockup for one of them:

![publishin_capture2](https://user-images.githubusercontent.com/33513211/89627365-085c0400-d89b-11ea-915a-5e8779b4a74f.gif)

It would be rendered in backgound of plugin item.

Plugin can report its progress just by outputting it to log in some specific format:

```
self.log.info("progress: 20%")
```
Similar approach is taken in Deadline plugins. Advantage is that it is backwards compatible. If plugin doesn't output it, no progress indication will be rendered. If plugin ends up before reaching 100%, and it doesn't fail, progress bar is hidden.

[cuID:PYPE-1122]

**Comment by mkolar** [comment]
I like it. Good place to show it as well

**Comment by mkolar** [comment]
related comment to this in #476

**Comment by BigRoy** [comment]
> self.log.info("progress: 20%")

It might be more explicit by a Pyblish method on the Plugins by default, like `Plugin.set_progress(value)` so you could do: `self.set_progress(0.2)` or alike. The text parsing of output makes sense for something like Deadline since it's parsing applications out of their control but for Plugins we control ourselves it might make more sense to call it explicitly. It also avoids needless logging/printing of the percentage too.

Then pyblish could even have a master logger that could keep track of a progress logging interval (e.g. log percentage every x seconds) if you'd still want the percentages logged to stdout e.g. when running a Pyblish task in Deadline or alike?

---

This is related to this Pyblish QML issue: https://github.com/pyblish/pyblish-qml/issues/141

**Comment by antirotor** [comment]
I agree that explicit `set_progress` is better as we have direct control over used plugins.
